### ISSUE TITLE
Approaches for Live App Testing

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#101]
Hi @IreneCMT , so for the live app testing we want to do in the final week of the project. I think there are two approaches depending on availability. 

**Option 1**
We give to the one therapist you've mentioned and ask her to use it for 1 week with a series of challenges (e.g. set up clients, add programmes). We would be on direct call throughout if there are any issues, so we can identify pain points, and then we would have a final interview at the end to go through usability

**Option 2**
It is much more similar to the round of testing we did before, except with the live app rather than Figma. So we carry out 30-45 minute interviews with a series of clients and therapists, giving them some tasks and simulating certain scenarios using dummy logins/accounts. This would then get synthesised into feedback and potential changes for future work. 

I would say we should look at at least a bit of option 2 even if it's not initially with as many people in that week (since we may not have enough allocated time in our budget) to get a good range of feedback. 

Maybe it's a combination of option 1 and 2? What do you think?

**Comment by IreneCMT** [comment]
Hi @thejoefriel Yes, in principle I am more inclined for plan 1 because that is what we have organised already, but we could try and get another therapist involved at this stage.  It is hard to get people onboard for these things but I can try to recruit some more therapists/clients.
You say this is for the last week, so is it week 10? I thought it would be week 8. I don't mind either way, but to plan accordingly. 
Thanks x

**Comment by thejoefriel** [comment]
Hi @IreneCMT so to confirm on this the dates would be from 22nd April at the earliest, as this then gives us time to fix bugs. Hope that makes sense! 

Did you have any luck recruiting any other therapists or clients? If not then as you say let's proceed with plan 1 and I can write up the challenges this week?
