### ISSUE TITLE
Unable to update the programme description

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#193]
**Bug**
Unable to update the programme description. See video

**Notion**
23
https://www.notion.so/3f7ac9a10d934626816587594ce473e7?v=82bea5ffa6cf4b73ab1b716d6a54805f

**Comment by dupreesi** [comment]
@thejoefriel @RamyAlshurafa this bug happens because of these bugs #182. More precisely when editing a programme with content that has 0 categories validation of that content throws an error. So this bug has actually nothing to do with the description and should be fixed when re-factoring the categories management. Keep it open to double check once #182 is solved.

**Comment by thejoefriel** [comment]
Thanks @dupreesi
