### ISSUE TITLE
Viewing an update from a discharged/deleter user

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#248]
**Flow**
- Created a programme for a client
- Client provided an update 
- I sent a reply to the update
- The client then deleted themselves
- I viewed the programme and it said there was an update
- When I clicked to view the update the page loads, but there's just a loading icon

**Further thoughts**
I believe this is because the update video has been deleted like it should, but it's still trying to fetch it. Instead we should just add text instead that says "Since this client has deleted their account you are no longer able to view their update."

**Comment by RamyAlshurafa** [comment]
@thejoefriel im not able to see 'View update" button, because we delete the updates with the user, so i think you were able to see it because you didnt reloaded the page after you deleted the client, right?
for now even if this edge case happened i redirect to 404 page, because im not able to know if the user therapist used a wrong url like `http://localhost:3000/therapist/update/wrong_id` or it has been deleted because the client is deleted
