### ISSUE TITLE
Consequence Scanning

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#5]
### Summary
With an idea of what we're looking to build, it is important to consider all the potential consequences this tool might have. This will help us:

- Identify important elements to consider as we further define our user journeys
- Develop the foundations for a risk assessment of the product

### Links
https://whimsical.com/consequence-scanning-R2VK5TbvGpkxtn94844WR7

### Video of Session
https://drive.google.com/file/d/1lWeWXZUXiG7rTQAdVb9nToGFpBzs5a1P/view?usp=sharing

**Comment by IreneCMT** [comment]
Great session on consequence scanning today @thejoefriel and @dupreesi. Thanks for your input. I'll share this with the team and add any more that may come up

**Comment by IreneCMT** [comment]
Where can we find the recording of this session @thejoefriel ? tks

**Comment by thejoefriel** [comment]
Hey @IreneCMT I've added the video link for the session on the issue for you! I've also tidied up the Consequence Scanning  document as well so hopefully easier for people to add!

**Comment by IreneCMT** [comment]
Fab, thanks Joe!


Irene Lo Coco
Music Therapist
Chiltern Music Therapy

Music Therapist
HCPC registration AS16187

M		07512 537819
T		01442 780541
E		irene@chilternmusictherapy.co.uk
W		www.chilternmusictherapy.co.uk
  
Chiltern Music Therapy Community Interest Company No. 7702358
Registered address: Irfon House, Stones Courtyard, High Street, Chesham, Buckinghamshire, HP5 1DE
  
This e-mail and any attachments are confidential and intended solely for the addressee. If you are not the addressee or have received this e-mail in error, please notify the sender immediately, delete it from your system and do not copy, disclose or otherwise act upon any part of this e-mail or its attachments.
