### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#7]
### Summary
This issue is to build out all the steps for each user journey (i.e. what are all the steps in which the user will interact with our digital platform to reach the final outcome) 

Something we find very helpful to do is also always bear in mind how the user is feeling. Are they strapped for time (e.g. maybe they have 10 minutes in between making dinner for the family), are they feeling anxious, are they making an important decision etc? This helps us constantly review our steps and see what information we need to provide to best get them to their goal. 

### Example Template:
<img width="699" alt="Bildschirmfoto 2020-11-23 um 18 31 34" src="https://user-images.githubusercontent.com/23721486/100000875-269e2f00-2dba-11eb-9504-2113f12694e6.png">

### Presentation for more information:
https://docs.google.com/presentation/d/1JWVDThFGPnLyM5Dmw5hpN_6v87gHaj8_djWh1maTrBg/edit?usp=sharing

---

### Links
https://whimsical.com/user-journey-mapping-user-stories-QgyjbzYbBxEwqMgq6Zx2Q8

---

### Workshop Recordings
Pt 1: https://drive.google.com/file/d/1G-2uc6CsRZQsLh7FbaMlOqztTkxhoRqn/view?usp=sharing
Pt 2: https://drive.google.com/file/d/12QWy7i0uiYp-ytBaeeS7GXTuryKRd-rQ/view?usp=sharing

**Comment by IreneCMT** [comment]
Hi @thejoefriel and @jema28
I've been reading through the user journeys again as discussed,. All looks pretty good and thorough, but I've added a few comments below, as I wasn't able to add comments in there (view only version), 
client journey: 
- I think it is fine to say "your therapist" instead of the therapist's name. 
- we need to confirm whether all videos will be password protected and review that opening line in regards to reassuring clients of data safety
- On personal details story: do we need to anonymise this data? i.e. initials instead of client's name
